# databases:
#   - name: asap-task
#     databaseName: asap
#     user: asap
#     plan: free
#     region: singapore

# services:
#   - type: web
#     name: asap-task
#     env: ruby
#     plan: free
#     region: singapore
#     buildCommand: "./bin/render-build.sh"
#     startCommand: "bundle exec puma -C config/puma.rb"
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: asap-task
#           property: connectionString
#       - key: RAILS_MASTER_KEY
#         sync: false
databases:
  - name: mysite
    databaseName: mysite
    user: mysite
    plan: free

services:
  - type: web
    name: mysite
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
